name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: yarn
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test